### PR TITLE
support pod mode

### PR DESCRIPTION
**Pull request by houfeng0923**

### CODE REVIEW

**Comment by cs3b** [comment]
this should be close, as the logic have been extracted to the 

https://github.com/josa42/ember-find-related-files

And needs to be ported there, as ember-fin-related-files do not support pods structure (witch is pretty common)

**Comment by cs3b** [comment]
I've write part of the implementation (only for components, without routes and controllers - as those are less popular part of pod system). 

https://github.com/josa42/ember-find-related-files/pull/1 

How can I help to push it forward ?

**Comment by cs3b** [comment]
Here is the package with support for the components in pods (before the official one will be released)

[ember-related-files-1.2.1.vsix.zip](https://github.com/josa42/vscode-ember-related-files/files/1211873/ember-related-files-1.2.1.vsix.zip)

**Comment by jamesdixon** [comment]
@josa42 any chance this gets merged soon? my app is all pods

**Comment by dguayrobotiq** [comment]
@cs3b I installed the `.vsix` in VS code but the shortcut does nothing. Is this suppose to work?

**Comment by cs3b** [comment]
@dguayrobotiq I've developed when experimental pods support was available, and as I mention it only have support for components, and as you can see on gif it works (cmd+alt+r / ctr+alt+r on windows).

cmd_alt_r

For the module unification [RFC 143](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md) - this plugin needs to be rewritten (as it is now much easier to navigate between related files)

**Comment by dguayrobotiq** [comment]
@cs3b It doesn't seem to work for me. CMD+ALT+R does absolutely nothing whether I'm in a component or template.

**Comment by cs3b** [comment]
@dguayrobotiq if there is nothing that capture that shortcut, it's hard to say why it does not work for you.

What about launching command by name (cmd+p)

screen shot 2018-02-07 at 19 48 56

**Comment by dguayrobotiq** [comment]
@cs3b Still nothing

**Comment by dguayrobotiq** [comment]
@cs3b Any way you could help me further on this? I'd really like to have this feature in my day-to-day !

**Comment by cs3b** [comment]
@dguayrobotiq can you show me your directories structure (if you are using the module unificaiton, it might be a problem) ?

**Comment by dguayrobotiq** [comment]
Components are in `/app/pods/components`. So if I have a component named `my-component`, it will look like:

`/app/pods/components/my-component` then inside that folder there is `component.js`, `template.hbs` and `styles.scss`

**Comment by jamesdixon** [comment]
@dguayrobotiq that could be your issue. As far as I know, by default, pods are just setup under the `components/` directory. When I do `ember g <component> --pod` that's where they end up for me.

**Comment by cs3b** [comment]
@dguayrobotiq yeap, @jamesdixon is right, taking into account the pods in general are more simpler, it would be possible to rewrite some rules to get this functionality also on tree structure like yours (still have no time this week to do this), Maybe next one ...

**Comment by lolmaus** [comment]
So pod support is currently unavailable?

**Pull request closed without merging**
